apiVersion: v1
kind: Service
metadata:
  name: innovatech-despachos
  namespace: innovatech
spec:
  selector:
    app: innovatech-despachos
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer